# Generated by Django 4.0.4 on 2022-05-16 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemcategory', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=366)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Registration',
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_color', models.CharField(max_length=100)),
                ('item_description', models.TextField(max_length=100)),
                ('item_quantity', models.IntegerField()),
                ('item_price', models.IntegerField()),
                ('for_gender', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cshopapi.category')),
            ],
            options={
                'db_table': 'Clothes',
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField()),
                ('deliveryCity', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=200)),
                ('receiver_id', models.IntegerField()),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cshopapi.registration')),
            ],
            options={
                'db_table': 'Checkout',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cshopapi.clothes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cshopapi.registration')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
