# Generated by Django 4.0.4 on 2022-05-17 07:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cshopapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='receiver_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothes',
            name='item_image',
            field=cloudinary.models.CloudinaryField(default='images', max_length=255, verbose_name='image'),
        ),
    ]
